baseURL = 'https://w1torres.github.io/concurso-hugo/'
languageCode = 'pt-br'
title = 'Estudo para Concursos'
theme = 'hugo-book'

[params]
  # Configurações do tema Hugo Book
  BookToC = true
  BookSearch = true
  BookRepo = "https://github.com/w1torres/concurso-hugo"
  customCSS = ["css/custom.css"]
[menu]
  [[menu.before]]
    name = "Disciplinas"
    url = "/"
    weight = 1